### PR TITLE
Bulk Exporter

### LINKED ISSUE #17: Better Support for Batch Uploads of Historical HealthKit Data
### Problem

[Our application](https://github.com/CS342/2024-Prisma) relies on uploading 3 months of historical HealthKit data to our Firebase. In our application delegate, we have the following code
```
class PrismaDelegate: SpeziAppDelegate {
    override var configuration: Configuration {
        Configuration(standard: PrismaStandard()) {
            ... // Firebase configuration
            if HKHealthStore.isHealthDataAvailable() {
                healthKit
            }
            ... // other module initialization
        }
    }
    ...
    private var healthKit: HealthKit {
        HealthKit {
            CollectSamples(
                [
                    HKQuantityType(.stepCount),
                    ... // other sample types
                ],
                predicate: HKQuery.predicateForSamples(
                    withStart: Calendar.current.date(byAdding: .month, value: -3, to: .now),
                    end: nil,
                    options: .strictEndDate
                ),
                deliverySetting: .anchorQuery(.afterAuthorizationAndApplicationWillLaunch)
            )
        }
    }
```

While this code largely works, we have encountered several issues related to batch historical data uploads:
1. **Firebase rate limiting**

We occasionally encounter the following error,
> `[FirebaseFirestore][I-FST000001] WriteStream (11df9e618) Stream error: 'Resource exhausted: Write stream exhausted maximum allowed queued writes.'`

  which I believe is due to Firebase [rate limiting](https://cloud.google.com/firestore/docs/best-practices#designing_for_scale).

  > If you index a field that increases or decreases sequentially between documents in a collection, like a timestamp, then the maximum write rate to the collection is 500 writes per second. 

This is triggered in our application because we index on a timestamp field. 

2. **Missing entries (potentially due to rate limiting)**

The data in our Firebase is occasionally missing entries, which I suspect is due to the WriteStream error. For example, below I compare cumulative daily step count measured on an Apple Watch directly from the Apple Health app vs. computed from our Firestore entries (filtering out step count measurements from an iPhone). There are several days on which step count is slightly undercounted (bolded).

| Date | Health App  | Firebase |
| -- | -- | -- |
| Feb 11 | 11317 | **10457** | 
| Feb 12 | 8497 | 8497 |
| Feb 13 | 13140 | 13140 |
| Feb 14 | 9160 | **8942** |
| Feb 15 | 9679 | **9617** |
| Feb 16 | 15084 | 15084 |
| Feb 17 | 6209 | 6209 |
| Feb 18 | 7432 | 7058 |

3. **Batch upload status is not communicated to the user**

Three months of historical data is large (on the order of 1-3GB when measured across several test users) and this upload can take several hours to complete. I am not sure if it is possible to improve this upload speed in light of rate limiting. Regardless, the app stops uploading data when it enters into the background and this is not communicated in the UI. It would be highly desirable to have a progress bar indicating upload status and/or have a local notifications trigger when the application enters the background with instructions for the user. This is a design pattern employed by many other iOS applications (e.g., Spotify, Google Drive) for long-running network tasks. 

### Solution

I have briefly chatted with @PSchmiedmayer about possible solution strategies. We spoke about adding additional functionality for batch uploads to the SpeziHealthKit module by
* Querying HealthKit data in smaller batches (say of size 100-500 entries) and processing these uploads on a 1s timer to avoid rate limiting
* Confirming that each entry was successfully uploaded to Firebase by performing a final read operation prior to dequeuing the upload
* Maintaining some notion of queue status in local storage such that the upload queue is paused without data loss when the application enters the background
* Exposing a [Progress](https://developer.apple.com/documentation/foundation/progress) object that can be used to render a progress bar

@PSchmiedmayer feel free to chime in here with more implementation-specific details or if I missed something!

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by lukaskollmer**
# Bulk Exporter

## :recycle: Current situation & Problem
this PR adds a bulk exporter API, which allows apps to use SpeziHealthKit to export large amounts of historical HealthKit data in an organized and coordinated way, with automatic persistence and state restoration across multiple app launches.

the fundamental idea is to have a `BulkExporter` API that the app would just inform about the to-be-exported sample types, and the BulkExporter would then do all of the (batched) fetching and processing (customizable by the app), and would simply inform the app about the results of these batches.
the `BulkExporter` would then also keep track of which batches have already been processed, and which are still pending, and be able to continue this work across multiple app launches.
additionally, the `BulkExporter` will be able to process the sample batches into different formats, so that you can eg say "i want each batch to become a compressed JSON archive", or "i want each batch to be added to my database", etc.

merging this PR would also close #17

## :gear: Release Notes
- added `BulkHealthExporter` module.

## :books: Documentation
the DocC extension file for the new `BulkHealthExporter` will contain documentation for the export mechanism, including code samples

## :white_check_mark: Testing
there is a new UI test to test the bulk exporter. (we can't do this in a non-UI unit test, since we need to add HealthKit samples in order to have something to test against.)

## :pencil: Code of Conduct & Contributing Guidelines
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: Sources/SpeziHealthKit/Bulk Export/BulkHealthExporter+Session.swift [hunk 1]
```diff
@@ -0,0 +1,378 @@
...
+    /// ## Topics
+    /// ### Session Lifecycle Management
+    /// - ``start()``
+    /// - ``pause()``
+    /// ### Session State
+    /// - ``isRunning``
+    /// - ``state``
+    /// - ``progress``
+    @Observable
+    public final class ExportSession<Processor: BatchProcessor>: Sendable, ExportSessionProtocol {
```
Comment (lukaskollmer) [inline Sources/SpeziHealthKit/Bulk Export/BulkHealthExporter+Session.swift:156]: the type is currently called an `ExportSession`. previously it was just called a `Session`. i'm not really happy with either of these names, we might want to call it an `ExportTask` instead?

**Review by PSchmiedmayer — COMMENTED** [review]
I forgot to publish some comments I had while looking through the diff. Only minimal things compared to the things we discussed in the meeting today.

File: Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift [hunk 2]
```diff
@@ -0,0 +1,260 @@
...
+        }
+        .task {
+            await fetchNumTestingSamples()
+        }
+    }
+    
+    @ViewBuilder private var actionsSectionContent: some View {
+        AsyncButton("Request full access", state: $viewState) {
+            let sampleTypes: [HKSampleType] = self.sampleTypes.effectiveSampleTypesForAuthentication.map { $0.hkSampleType }
+            try await healthKit.askForAuthorization(for: .init(
```
[the remark this answers is not in the document]
Comment (lukaskollmer) [reply Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift:93]: i changed this already yesterday to always implicitly perform the effective sample types transformation when dealing with auth stuff (https://github.com/StanfordSpezi/SpeziHealthKit/pull/48/commits/5bdfcca8e13caf7e85fbb9aaeb190cd2ac447f0a), but i forgot to remove the code from the TestApp

File: Sources/SpeziHealthKit/Sample Types/WrappedSampleType.swift [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+
+import Foundation
+import HealthKit
+
+
+/// An enum for working with ``SampleType``s in non-generic contexts.
+///
+/// This utility type is useful for APIs which operate on heterogeneous collections of ``SampleType``s,
+/// and in contexts where generics aren't easily available, e.g. when using ``SampleType``s as `Codable` properties.
+public enum WrappedSampleType: Hashable, Identifiable, Sendable {
```
[the remark this answers is not in the document]
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKit/Sample Types/WrappedSampleType.swift:29]: I agree that this is not ideal but there is no good way around this. The overall solution is elegant. 

`WrappedSampleType` is good, I like `SampleTypeProxy` a bit more and agree that an alignment with FHIRModels might be nice. But not a huge preference, I can live with both.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift [hunk 4]
```diff
@@ -0,0 +1,241 @@
...
+            break
+        }
+        task?.cancel()
+    }
+}
+
+
+// NOTE: in Swift 6.0.3, we need to place this enum in the global scope, since nesting it in `BulkHealthExporter.ExportSession`
+// (where it belongs) will cause the compiler to crash.
+// Whatever the actual underlying issue here is, it seems to be fixed in Swift 6.1, so we'll hopefully be able to move this type soon.
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/BulkExportSession.swift:217]: IMO we could put the Swift Package version to 6.1 here?

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+    case paused
+    /// The session is currently running.
+    case running
+    /// The session has completed its work, and has nothing else left to do.
+    case done
+}
+
+
+/// Information about the current progress of a ``BulkExportSession``.
+public struct BulkExportSessionProgress: Sendable {
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift:28]: I am wondering if we should expose a nice mechanism to get a Foundation `Progress` type here or somewhere else? Would make it easy to interface with some SwiftUI views, e.g., https://developer.apple.com/documentation/swiftui/progressview/init(_:)-l5vj. 

Also wondering if we should expose the number of failed batches here as well? And/or an error attached to each failed batch? Could be included in the progress indicator (also counts failed batches to it will reach 100%).

File: Sources/SpeziHealthKitBulkExport/ExportSessionStartDate.swift [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+    /// If there is no component with a non-nil and non-zero value, the behaviour will be equivalent to `ExportSessionStartDate.oldestSample`.
+    ///
+    /// For example:
+    /// - `ExportSessionStartDate.last(DateComponents(year: 2))` will collect the last 2 years of historical data;
+    /// - `ExportSessionStartDate.last(DateComponents(month: 18))` will collect the last 18 months of historical data;
+    /// - `ExportSessionStartDate.last(DateComponents(year: 2, month: 1))` will collect the last 25 months of historical data.
+    case last(DateComponents)
+    
+    /// The session should use a specific `Date` as its start date.
+    case custom(Date)
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/ExportSessionStartDate.swift:35]: Maybe rather `absolute`/`fixed` or something like this?

File: Sources/SpeziHealthKitBulkExport/ExportSessionStartDate.swift [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+}
+
+
+extension ExportSessionStartDate {
+    /// The session should, relative to the time it was first created, collect the last `numMonths` of historical Health data.
+    public static func last(numMonths: Int) -> Self {
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/ExportSessionStartDate.swift:41]: An overload for years and days might also be nice.

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:1]: Thank you for all the documentation here!

File: Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift (hunk 2 above)
[the remark this answers is not in the document]
Comment (PSchmiedmayer) [reply Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift:105]: Nice, thank you!

File: Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift
Comment (PSchmiedmayer) [inline Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift:1]: Wondering if we can, at some point, add a nice UI for tracking the bulk export status + a retry button on failure as well as some error descriptions in a separate UI target there. Might be something nice after we tested the feature and built some UI around this in other apps.

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for all the work here; looks really nice. Happy to see this merged once our elements from the discussion yesterday and my comments are incorporated 🚀

CC @mjoerke, this might be very helpful for future versions of our research study as well.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift (hunk 4 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSession.swift:225]: we don't yet have Xcode 16.3; also, nesting this is probably no longer really important since we now have a dedicated target for the exporter

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift:28]: we're now (this is one of the changes in response to our discussion yesterday) exposing all individual pending/failed/completed batches as part of the `ExportSessionProtocol`, which also gives access to the number of samples (`session.failedBatches.count`). we also have `session.pendingBatches` and `session.completedBatches`.

regarding the progress: i was actually thinking about getting rid of the `BulkExportSessionProgress` type (or at least cut it down to only the `batchDescription`, since the other elements (`#completed` and `#total`) are now exposed on the session directly. we could just have a `Progress?` property on the session, which would be `nil` for paused sessions, and nonnil for runnig sessions

File: Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift
Comment (lukaskollmer) [reply Tests/UITests/TestApp/HealthKitTestsView/BulkExportView.swift:1]: i'll open an issue once this is merged 👍

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+                session.start()
+            }
+            return .newSession(session, stream)
+        }
+    }
+    
+    /// Deletes the persisted state restoration info for a session created in during previous launch of the app, based on its identifier.
+    ///
+    /// - Note: This function can only be used to delete sessions that have not yet been restored during the current lifetime of the app.
+    ///     Once a session identifier has been passed to ``session(_:for:startDate:endDate:batchSize:using:startAutomatically:)``, it cannot be passed to ``deleteSessionRestorationInfo(for:)`` anymore.
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:97]: What is the reason for this? Wouldn't it be great to create a session identifier as a static constant as an extension to `BulkExportSessionIdentifier` to use the dot syntax across the app? What is the core reason for keeping this limitation around?

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+        /// The ``BulkHealthExporter`` was unable to delete the session, since there is already a matching registered session.
+        case unableToDeleteRegisteredSession
+    }
+    
+    /// The result of obtaining a ``BulkExportSession`` through the ``BulkHealthExporter``.
+    public enum ObtainSessionResult<Processor: BatchProcessor> {
+        /// The ``BulkHealthExporter`` created a new session.
+        ///
+        /// This case encapsulates both the newly created session, as well as an `AsyncStream` for getting the individual batch processing results.
+        case newSession(BulkExportSession<Processor>, AsyncStream<Processor.Output>)
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:47]: What about moving the async stream as a response to the start function instead of the creation of the `BulkExportSession`? Would make this return cleaner and could allow us to easily attach this to a start of the export? And could also then make the start function either return an async stream or non if the output type is `Void`?

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+        }
+        try await batch.commit()
+    }
+}
+```
+
+We can then use the batch processor when creating a Bulk Export Session:
+```swift
+_ = try await bulkExporter.session(
+    "my-bulk-export-session",
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:63]: This example still uses a string identifier; should we demonstrate that we can have a static property as an extension to the identifier? Would be a good way to communicate the best practices.

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+            try batch.setData(from: sample.resource(), for: document)
+        }
+        try await batch.commit()
+    }
+}
+```
+
+We can then use the batch processor when creating a Bulk Export Session:
+```swift
+_ = try await bulkExporter.session(
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:62]: I think we should extend this example to call the start function to show the complete flow what you need to do + use the return type. I think there will never be a use case to not use it as we need to call start explicitly? Or at least IMO we should always enforce that a user needs to call start.

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md [hunk 12]
```diff
@@ -0,0 +1,97 @@
...
+This allows an app to e.g. use the `CollectSample` API to continuously fetch and collect new Health samples, and use the ``BulkHealthExporter`` to do a one-time export operation of historical Health data.
+
+The ``BulkHealthExporter/session(_:for:startDate:endDate:batchSize:using:startAutomatically:)`` function will, when a ``BulkExportSession`` is first created, also return an `AsyncStream` which can be used to access the individual results of the session's ``BatchProcessor``.
+
+- Important: Ensure that your app has sufficient HealthKit access permissions before starting bulk export sessions. The session itself will *not* prompt the user for access; instead, it will fail to fetch and process any sample types for which no HealthKit permission is granted.
+
+It is possible to ``BulkExportSession/pause()`` an export session, which can then be resumed using the ``BulkExportSession/start(retryFailedBatches:)`` function.
+
+
+### Example: Bulk-Upload of Historical Health Data to Firebase
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:42]: It would be great to also add an example of a `BatchProcessor` that uses an output type and how to properly use the async sequences.

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift:28]: Good idea to move the progress right in the session. I like them to just be exposed right there.

And the `Progress` could just be a convenient computed property exposed in addition based on all the other values so a user can easily plug it into a SwiftUI view.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift (hunk 4 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSession.swift:225]: Sounds good, you are right. Not really a problem.

**Review by PSchmiedmayer — APPROVED** [review]
Very nice, great to see all the advancements 🚀

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift:28]: since it's a class it can't be a computed property. [`Progress`](https://developer.apple.com/documentation/foundation/progress) isn't Observable, but it is KVO compliant (it's that old...) so my guess is that the `ProgressView` uses that internally when initializing it with a `Progress` instance

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 8 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:97]: we keep the sessions around once they're created, and even if we remove them from the `BulkHealthExporter`s internal array, we can't prevent the app from retaining a reference and just manually restarting it later on even though the session's underlying `LocalStorage`-managed descriptor would've been deleted.

we could add a mechanism where a session can be put into a non-exitable "terminated" state, which would cause all `start()` calls to become no-ops.

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift:28]: Oh, interesting, so we would need to manually update the stored instance? Might still be valuable to do that but you are right, not be best use of modern Swift.

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md (hunk 10 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:63]: the docs haven't been updated yet bc i wanted to wait for your feedback on the API changes

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md (hunk 11 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:62]: currently creating the session still will automatically start it. i can remove that behaviour and require an explicit call to `start()`

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 8 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:97]: I agree that there should be a mechanism to "terminate" a session when it is deleted. IMO it might even be fine for `start` to throw an error in that case, could communicate this to the developer/user.

I think it would be good to be able to use the same identifier in a way that it can be passed to `session...` and `delete` within the lifetime to the app, recreating it would be a thing that is normally not expected for identifiers.

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 9 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:47]: `start()` is currently allowed to be called multiple times, with any calls when the session is already running being no-ops.

i feel like having `start()` return the stream would not be the best idea; with the current design of `start()` and `pause()` returning void, it's easy to allow eg a UI component to control the export session, without requiring it to also deal with the actual batch processing results (which is the resposibility of the part of the code that starts the export session). otherwise, every place in the app that pauses/restarts a session would need to implement handling the results, and the app as a whole would need to somehow coordinate all of these.

regarding the Void-Output-based overloading: we should be able do that, though IMO we should rather do it with the `BulkHealthExporter.session()` function instead of `Session.start()`

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md (hunk 11 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:62]: I think that would make sense + would align with exposing the async sequence at this point. Also then makes the lifetime of the AsyncSequence easier.

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 9 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift:47]: @PSchmiedmayer what's your opinion here? do you see any potential issues with making the `start()` caller responsible for handling the session's batch results?

as stated above, this would IMO make it difficult to allow easily integrating session control into the UI.

typically, the part of the codebase that defines and creates the export session would also be the part that wants to receive and handle the individual batch results produced by the transformer; i can't really see any benefit from making the UI have to deal with this instead.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift [hunk 13]
```diff
@@ -23,7 +23,6 @@ import SpeziLocalStorage
 /// ### Session State
```
Comment (PSchmiedmayer) [inline Sources/SpeziHealthKitBulkExport/BulkExportSession.swift:23]: It might make sense to add some of the other properties about the different batches here / align the documentation in `BulkExportSessionProtocol` and here.

File: Package.swift
Comment (PSchmiedmayer) [inline Package.swift:1]: There is a warning in `Sources/SpeziHealthKitUI/HealthChart/HealthChart.swift` that _"value 'date' was defined but never used; consider replacing with boolean test"_. We might also want to resolve that by removing it, there is a commented out line in there.

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 9 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift]: II see two possible mechanisms here:
1. Output is `Void`, therefore start doesn't return a stream and there is no stream to keep track of.
2. Output is non-void in which case we will get the output and have to keep track of it.

In both cases, the progress and eventual errors can be observed using all the properties that a session exposes.

I think that it is fine if a UI keeps track of these elements, but a better way (and what we should probably demonstrate in some of the documentation) would be writing an own `Module` or view model that creates a session and then keeps track of the AsyncStream output. This would also be the desired setup if we would attach the stream to the `session` call.
But in general there might not be any harm if a View `.task` modifier or similar element would keep track of it if needed and just wants to use the output to update some UI.

If we expose an async stream a second start call should probably throw an error to indicate that the session is already running.

**Review by PSchmiedmayer — APPROVED** [review]

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift]: would we want the `Progress` to be relative the the total number of batches, or should it exclude failed batches?

ie, if we have 10 batches, 8 of which were processed successfully and 2 of which failed (and were scheduled for an automated retry next launch or earlier if explicitly requested): should the progress at the end be 80% or at 100%?

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md (hunk 12 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md:42]: added a second one that is essentially the MHC BatchProcessor minus the compression. also neatly demonstrates that you can combine this API with eg HealthKitOnFHIR to process the samples into another format

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 9 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift]: that's exactly how i ended up implementing it. agree regarding the `Module` / view model point.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift (hunk 13 above)
Comment (lukaskollmer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSession.swift:23]: i'll rework it to have the protocol be called `BulkExportSession`, rename the actual implementing class to `BulkExportSessionImpl` and make it private; that way we're not exposing the whole interface twice. since the protocol existentials can still carry the generic parameter, it'll work and behave exactly as if we were exposing the type directly.

File: Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift (hunk 5 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSessionProtocol.swift]: So it would mean that it would be 80% complete in the example? I think that makes sense. Would probably also make sense when we add an automatic retry in the future.

File: Sources/SpeziHealthKitBulkExport/BulkExportSession.swift (hunk 13 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkExportSession.swift]: Sounds good!

File: Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift (hunk 9 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/BulkHealthExporter.swift]: Thank you!

File: Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md (hunk 12 above)
Comment (PSchmiedmayer) [reply Sources/SpeziHealthKitBulkExport/SpeziHealthKitBulkExport.docc/BulkHealthExporter.md]: Thank you!
